apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-evict
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: node
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: 1Gi
              cpu: 10
            requests:
              memory: 256Mi
              cpu: 5