apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: github-build
spec:
# 设置参数 可以设置默认值 没提供就使用默认值
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
    default: cncamp/httpserver:v1.0
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./httpserver/Dockerfile
  - name: KanikoDockerContext
    description: context
    default: ./httpserver"
  resources:
    inputs:
    - name: repo
      type: git
  steps:
  - name: github-build
    image: cncamp/executor
    workingDir: /workspace/repo
    args:
    - "--dockerfile=${params.DOCKERFILE}"
    - "--context=${params.KanikoDockerContext}"
    - "--destination=${params.IMAGE}"
  workspaces: #定义一个workspace卷,在运行task时必须要提供一个workspace卷,我们可以用这个卷进行持久化,这个卷是针对task中的所有容器的。
  - name: dockerconfig
    description: Includes a docker `config.json`
    optional: true
    mountPath: /kaniko/.docker

