apiVersion: sources.knative.dev/v1beta2
kind: PingSource
metadata:
  name: knative-hello-ping-source
spec:
  schedule: "*/1 * * * *"
  data: '{"message": "Hello from KBE!"}'
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1
      kind: Channel
      name: knative-hello-channel
---
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: knative-hello-subs
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: knative-hello-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: fn