apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service0
spec:
  gateways:
    - service0
  hosts:
    - '*'
  http:
  - match:
      - uri:
          exact: /service0
    route: #转到 service0 的 80端口 这里 service 对应 envoy 的 cluster
      - destination:
          host: service0 #service0.tracing.svc.cluster.local fqdn
          port:
            number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway #负载均衡
metadata:
  name: service0
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - '*'
      port:
        name: http-service0
        number: 80
        protocol: HTTP
